import type { School } from "@/types/school";

/**
 * 화면 확인용 임시 데이터. 백엔드 폐교 목록 API 연결 시 이 파일만 제거하면 된다.
 * 실제 폐교 정보가 아니라 시안의 마스킹 표기(OO초등학교)를 그대로 따른 값이다.
 * 앞의 3건은 시안 데이터와 동일하고, 나머지는 탭 개수·더보기 확인용이다.
 */
export const MOCK_SCHOOLS: School[] = [
  {
    id: "school-01",
    name: "OO초등학교 OO분교장",
    address: "경북 포항시 OO면 OO리 OO",
    district: "포항시 OO면",
    closedYear: 2018,
    siteArea: 4500,
    classroomCount: 8,
    annexFacility: "강당",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "비교적 신축 · 유지관리 양호",
      access: "국도 인접 · 대중교통 하루 8회",
      surroundings: "해수욕장, 관광단지, 학원가 인접",
      details: "전기 · 화장실 양호 · 냉난방 설비 보유",
    },
  },
  {
    id: "school-02",
    name: "XX초등학교",
    address: "경북 포항시 OO읍 OO리 OO",
    district: "포항시 OO읍",
    closedYear: 2021,
    siteArea: 6200,
    classroomCount: 12,
    annexFacility: "급식실",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "일부 노후 · 옥상 방수 수리 필요",
      access: "시내버스 하루 12회 · 읍내 차량 10분",
      surroundings: "전통시장, 농공단지 인접",
      details: "전기 양호 · 화장실 개보수 필요 · 냉난방 미비",
    },
  },
  {
    id: "school-03",
    name: "YY초등학교",
    address: "경북 포항시 OO면 OO리 OO",
    district: "포항시 OO면",
    closedYear: 2016,
    siteArea: 5800,
    classroomCount: 10,
    annexFacility: "운동장",
    usageStatus: "일부활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "체육관 개보수 완료 · 교사동 양호",
      access: "국도 인접 · 대중교통 하루 6회",
      surroundings: "계곡, 캠핑장, 휴양림 인접",
      details: "전기 · 화장실 양호 · 냉난방 일부 설비",
    },
  },
  {
    id: "school-04",
    name: "AA초등학교 BB분교장",
    address: "경북 포항시 OO면 OO리 OO",
    district: "포항시 OO면",
    closedYear: 2019,
    siteArea: 3800,
    classroomCount: 6,
    annexFacility: "소강당",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "교사동 양호 · 창호 일부 파손",
      access: "지방도 인접 · 대중교통 하루 4회",
      surroundings: "농경지, 마을회관 인접",
      details: "전기 양호 · 상하수도 점검 필요 · 냉난방 미비",
    },
  },
  {
    id: "school-05",
    name: "CC초등학교",
    address: "경북 포항시 OO읍 OO리 OO",
    district: "포항시 OO읍",
    closedYear: 2013,
    siteArea: 7400,
    classroomCount: 14,
    annexFacility: "체육관",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "전반 노후 · 외벽 균열 확인 필요",
      access: "읍내 도보 15분 · 시내버스 하루 14회",
      surroundings: "농공단지, 보건지소 인접",
      details: "전기 재점검 필요 · 화장실 노후 · 냉난방 미비",
    },
  },
  {
    id: "school-06",
    name: "DD중학교",
    address: "경북 포항시 OO면 OO리 OO",
    district: "포항시 OO면",
    closedYear: 2020,
    siteArea: 9100,
    classroomCount: 18,
    annexFacility: "체육관, 급식실",
    usageStatus: "일부활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "본관 리모델링 완료 · 별관 미사용",
      access: "국도 인접 · 대중교통 하루 10회",
      surroundings: "산업단지, 근린공원 인접",
      details: "전기 · 화장실 양호 · 냉난방 전관 보유",
    },
  },
  {
    id: "school-07",
    name: "EE초등학교",
    address: "경북 포항시 OO동 OO",
    district: "포항시 OO동",
    closedYear: 2015,
    siteArea: 3100,
    classroomCount: 5,
    annexFacility: "없음",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "단층 교사동 · 부분 보수 이력",
      access: "시내 접근 양호 · 버스 하루 20회",
      surroundings: "주거밀집지, 상가 인접",
      details: "전기 양호 · 화장실 개보수 필요 · 냉난방 일부",
    },
  },
  {
    id: "school-08",
    name: "FF초등학교 GG분교장",
    address: "경북 포항시 OO면 OO리 OO",
    district: "포항시 OO면",
    closedYear: 2011,
    siteArea: 2700,
    classroomCount: 4,
    annexFacility: "창고동",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "장기 방치 · 구조 안전 확인 필요",
      access: "농로 경유 · 대중교통 하루 2회",
      surroundings: "산림, 저수지 인접",
      details: "전기 단절 · 상하수도 미연결 · 냉난방 없음",
    },
  },
  {
    id: "school-09",
    name: "HH초등학교",
    address: "경북 포항시 OO읍 OO리 OO",
    district: "포항시 OO읍",
    closedYear: 2022,
    siteArea: 5300,
    classroomCount: 9,
    annexFacility: "급식실",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "폐교 직후 · 시설 전반 양호",
      access: "읍내 차량 5분 · 시내버스 하루 16회",
      surroundings: "전통시장, 문화센터 인접",
      details: "전기 · 화장실 양호 · 냉난방 전관 보유",
    },
  },
  {
    id: "school-10",
    name: "II중학교",
    address: "경북 포항시 OO면 OO리 OO",
    district: "포항시 OO면",
    closedYear: 2017,
    siteArea: 8600,
    classroomCount: 16,
    annexFacility: "체육관, 강당",
    usageStatus: "일부활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "체육관 임대 운영 중 · 교사동 유휴",
      access: "국도 인접 · 대중교통 하루 8회",
      surroundings: "해안도로, 어촌계, 캠핑장 인접",
      details: "전기 양호 · 화장실 부분 개보수 · 냉난방 일부",
    },
  },
  {
    id: "school-11",
    name: "JJ초등학교",
    address: "경북 포항시 OO면 OO리 OO",
    district: "포항시 OO면",
    closedYear: 2014,
    siteArea: 4100,
    classroomCount: 7,
    annexFacility: "강당",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "지붕 누수 이력 · 교실 내부 양호",
      access: "지방도 인접 · 대중교통 하루 5회",
      surroundings: "과수단지, 마을회관 인접",
      details: "전기 양호 · 화장실 노후 · 냉난방 미비",
    },
  },
  {
    id: "school-12",
    name: "KK초등학교 LL분교장",
    address: "경북 포항시 OO면 OO리 OO",
    district: "포항시 OO면",
    closedYear: 2012,
    siteArea: 2400,
    classroomCount: 3,
    annexFacility: "없음",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "장기 방치 · 부지 정비 필요",
      access: "마을 진입로 경유 · 대중교통 하루 3회",
      surroundings: "산림, 사찰 인접",
      details: "전기 단절 · 화장실 사용 불가 · 냉난방 없음",
    },
  },
];
