import type { School } from "@/types/school";

/**
 * 화면 확인용 임시 데이터. 백엔드 폐교 목록 API 연결 시 이 파일만 제거하면 된다.
 *
 * 학교명 · 주소 · 폐교연도 · 대지면적 · 주변 자원은 경북 미활용 폐교 자료의
 * 포항시 8곳을 그대로 옮긴 값이다.
 * 교실 수 · 부속시설 · 시설 상태 · 접근성 · 시설 세부는 원자료에 없어 임시값이다.
 *
 * 첫 항목(송라중학교)은 목 기획안(mock-plan.ts)이 다루는 폐교라 목록 맨 앞에 둔다.
 */
export const MOCK_SCHOOLS: School[] = [
  {
    id: "school-01",
    name: "송라중학교",
    address: "경북 포항시 북구 송라면 광천리 184",
    district: "포항시 송라면",
    closedYear: 2026,
    siteArea: 14064,
    classroomCount: 8,
    annexFacility: "강당, 운동장",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "비교적 신축 · 유지관리 양호",
      access: "7번 국도 인접 · 대중교통 하루 8회",
      surroundings: "내연산, 보경사·12폭포, 화진해수욕장",
      details: "전기 · 화장실 양호 · 냉난방 설비 보유",
    },
  },
  {
    id: "school-02",
    name: "대보초등학교 대동배분교장",
    address: "경북 포항시 남구 호미곶면 대동배리 410-1",
    district: "포항시 호미곶면",
    closedYear: 2007,
    siteArea: 5500,
    classroomCount: 3,
    annexFacility: "창고동",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "폐교 후 장기 미사용 · 외벽 보수 필요",
      access: "해안도로 인접 · 대중교통 하루 6회",
      surroundings: "구룡소·호미반도 해안둘레길, 호미곶 관광지·국립등대박물관, 구룡포 관광권",
      details: "전기 양호 · 화장실 개보수 필요 · 냉난방 미비",
    },
  },
  {
    id: "school-03",
    name: "죽장초등학교 상옥분교장",
    address: "경북 포항시 북구 죽장면 상옥리 748-1",
    district: "포항시 죽장면",
    closedYear: 2026,
    siteArea: 10380,
    classroomCount: 6,
    annexFacility: "강당",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "최근 폐교 · 유지관리 양호",
      access: "지방도 경유 · 대중교통 하루 4회",
      surroundings: "상옥계곡, 하옥계곡, 포항학생야영장·산림휴양 자원",
      details: "전기 · 화장실 양호 · 냉난방 일부 설비",
    },
  },
  {
    id: "school-04",
    name: "장기초등학교 모포분교장",
    address: "경북 포항시 남구 장기면 모포리 95",
    district: "포항시 장기면",
    closedYear: 2026,
    siteArea: 6209,
    classroomCount: 4,
    annexFacility: "급식실",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "최근 폐교 · 시설 전반 양호",
      access: "해안도로 인접 · 대중교통 하루 9회",
      surroundings: "모포항, 모포해안·일출 명소, 구룡포·신창해수욕장 관광권",
      details: "전기 · 상하수도 양호 · 냉난방 보유",
    },
  },
  {
    id: "school-05",
    name: "신광초등학교 비학분교장",
    address: "경북 포항시 북구 신광면 만석리 800-68",
    district: "포항시 신광면",
    closedYear: 2007,
    siteArea: 19613,
    classroomCount: 8,
    annexFacility: "강당, 운동장",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "교사동 양호 · 지붕 방수 이력",
      access: "지방도 인접 · 대중교통 하루 7회",
      surroundings: "비학산, 법광사, 비학산 자연휴양림",
      details: "전기 양호 · 화장실 노후 · 냉난방 미비",
    },
  },
  {
    id: "school-06",
    name: "이가초등학교",
    address: "경북 포항시 북구 청하면 이가리 138",
    district: "포항시 청하면",
    closedYear: 1996,
    siteArea: 8418,
    classroomCount: 12,
    annexFacility: "체육관, 급식실",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "장기 방치 · 구조 안전 확인 필요",
      access: "동해대로 인접 · 대중교통 하루 12회",
      surroundings: "이가리 닻 전망대, 이가리 간이해수욕장, 월포해수욕장",
      details: "전기 단절 · 화장실 사용 불가 · 냉난방 없음",
    },
  },
  {
    id: "school-07",
    name: "기계초등학교 기서분교장",
    address: "경북 포항시 북구 기계면 가안리 14",
    district: "포항시 기계면",
    closedYear: 2002,
    siteArea: 12777,
    classroomCount: 6,
    annexFacility: "강당",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "부분 보수 이력 · 창호 교체 필요",
      access: "국도 인접 · 대중교통 하루 10회",
      surroundings: "기계서숲, 새마을운동발상지기념관, 비학산·운주산 산림자원",
      details: "전기 양호 · 화장실 개보수 필요 · 냉난방 일부",
    },
  },
  {
    id: "school-08",
    name: "대보초등학교 강사분교장",
    address: "경북 포항시 남구 호미곶면 강사2리 491",
    district: "포항시 호미곶면",
    closedYear: 1993,
    siteArea: 7422,
    classroomCount: 4,
    annexFacility: "없음",
    usageStatus: "미활용",
    dataAsOf: "2026. 7.",
    facility: {
      condition: "장기 방치 · 부지 정비 필요",
      access: "해안도로 경유 · 대중교통 하루 5회",
      surroundings: "호미곶 해맞이광장, 국립등대박물관, 호미반도 해안둘레길",
      details: "전기 단절 · 상하수도 미연결 · 냉난방 없음",
    },
  },
];
